ProTwo/ProTwo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from appTwo import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^book/',include('appTwo.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^special/$', views.special, name='special')

]

ProTwo/appTwo/urls.py
from django.conf.urls import url
from appTwo import views

app_name = 'appTwo'
urlpatterns = [
    url(r'^$',views.clients,name='clients'),
    url(r'^register/$', views.book,name='book'),
    url(r'^login/$',views.user_login,name='user_login')
]

ProTwo/appTwo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ClientInfo(models.Model):
    #THIS IS LIKE EXTENDING THE CLASS TO ADD MORE FIELDS
    client = models.OneToOneField(User,on_delete=models.DO_NOTHING)
    #Adding the additional fields
    date = models.DateField()
    phone_number = models.CharField(max_length=13) #note, it does'nt start with models

    def __str__(self):
        return self.client.username
        #username is a default attribute
class Booking(models.Model):
    username = models.CharField(max_length=30,unique=False)
    email = models.EmailField(max_length=30,unique=True,blank=True)
    date = models.DateField()
    phone_number = models.CharField(max_length=13) #note, it does'nt start with models

    def __str__(self):
        return self.username

ProTwo/appTwo/forms.py
from django import forms
from django.contrib.auth.models import User
from appTwo.models import ClientInfo,Booking

class ClientDefaultInfoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ClientDefaultInfoForm,self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                     'class': 'form-control'
                 })
    class Meta():
        date = forms.DateField(input_formats=['%Y-%m-%d','%m/%d/%Y','%d/%m/%y'])
        model = User
        fields = ('username', 'email', 'password')
        labels = {
                "username":'Username :',
                "email":'Email Addr:',
                "password":'Password :',
        }
        widgets = {
        'username': forms.TextInput(attrs={'placeholder':'example: Touray'}),
        'email': forms.TextInput(attrs={'placeholder':'example: touray@gmail.com'}),
        'password': forms.PasswordInput(attrs={'placeholder':''})

        }
#THIS IS THE FORM FOR THE EXTENDED FIELDS
class ClientInfoForm(forms.ModelForm):
    #THIS CODE FORMATS THE FORM FIELD IN A NICE WAY
    def __init__(self, *args, **kwargs):
        super(ClientInfoForm,self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                     'class': 'form-control'
                 })
    class Meta():
        model = ClientInfo #never put a capital letter on 'models'
        fields = ('date','phone_number')
        labels = {
                "date":'Select Date:',
                "phone_number":'Phone No.  :'
            }
        widgets = {
        'date': forms.TextInput(attrs={'placeholder':'example: 2020-05-30'}),
        'phone_number': forms.TextInput(attrs={'placeholder':'example: 9999999'})
        } #ADDING STUFFS LIKE placeholder TO THE FORM FOR GUIDE

#DEFINING THE FORM FOR THE APPOINTMENT MODEL(where users can book appointment)
class BookingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BookingForm,self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                 'class': 'form-control'
             })
    class Meta():
        model = Booking
        fields = ('username','email','date','phone_number')
        labels = {
            "username":'Username:',
            "email":'Email Address:',
            "date":'Select Date:',
            "phone_number":'Phone No:'
        }
        widgets = {
            'username': forms.TextInput(attrs={'placeholder':'example: Omar'}),
            'email': forms.TextInput(attrs={'placeholder':'example: omartouray@gmail.com'}),
            'date': forms.TextInput(attrs={'placeholder':'example: 2020-05-30'}),
            'phone_number': forms.TextInput(attrs={'placeholder':'example: 9999999'})
        }

ProTwo/appTwo/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

# from django.http import HttpResponse
# from appTwo.models import User
from appTwo.forms import ClientDefaultInfoForm, ClientInfoForm,BookingForm
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,'appTwo/base.html')

# sigup page, validation,commiting to databse and creation of a user
def clients(request):
    registered = False

    if request.method == "POST":
        client_form1 = ClientDefaultInfoForm(data=request.POST)
        client_form2 = ClientInfoForm(data=request.POST)

        if client_form1.is_valid() and client_form2.is_valid():
            client = client_form1.save() #grabbing data and saving it to the db
            client.set_password(client.password) #hashing the password_validation
            client.save()

            form2 = client_form2.save(commit=False)
            form2.client = client

            if 'client_form2' in request.POST:
                form2.client_form2 = request.POST['client_form2']
            form2.save()
            registered = True
        else:
            print(client_form1.errors, client_form2.errors)
    else:
        client_form1 = ClientDefaultInfoForm()
        client_form2 = ClientInfoForm()

    return render(request,'appTwo/registration.html',{'client_form1':client_form1,
                                                    'client_form2':client_form2,
                                                    'registered':registered})
# view function for the login, authentication, validation, password hashing
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        client = authenticate(username=username, password=password)

        if client: #this condition checks if the user has bee authenticated
            login(request,client)

            return HttpResponseRedirect(reverse('index'))

        else:
            print("Someone tried to login and failed")
            print("username {} and password {}".format(username, password))
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, 'appTwo/login.html')

#Using the decorator to condition the status of the user
@login_required # It has to be above the function
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
#using the decorator to condition the status of the user
@login_required # you have to log in to be able to be decorated by this
def special(request):
    return HttpResponse("You're logged-in!")


# view function for the booking page
def book(request):
    bookform = BookingForm()

    if request.method == "POST":
        bookform = BookingForm(request.POST)

        if bookform.is_valid():
            bookform.save(commit=True)
            return index(request) #This is how the homepage is return when validated
        else:
            print('ERROR FORM INVALID')
# rendering from book.html
    return render(request,'appTwo/book.html',{'bookform':bookform})

ProTwo/templates/appTwo/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
  </head>
  <body>
    <!-- Creating a navigation bar which is inherited by other templates -->
    <nav class="navbar navbar-expand-lg navbar-inverse">
      <div class="container">
        <ul class=nav navbar-nav>
          <!-- Users cannot logout if they have not log in -->
        <li><a class="navbar-brand" href="{% url 'appTwo:book' %}">BOOK AN APPOINTMENT</a></li>
        {% if user.is_authenticated %}
        <li><a class="navbar-brand" href="{% url 'user_logout' %}">LOGOUT</a></li>
        {% else %}
        <li><a class="navbar-brand" href="{% url 'appTwo:user_login'%}">LOGIN</a></li>
        {% endif %}
        <li><a class="navbar-brand" href="{% url 'appTwo:clients' %}">SIGNUP</a></li>
        <li><a class="navbar-brand" href="{% url 'admin:index'%}">ADMIN</a></li>

      </ul>
      </div>
    </nav>
    {% block body_block %}
    <div class="container">
      <div class="jumbotron">
        <h1>WELCOME TO XXX'S BARBING SALON!</h1>
        <h2>YOU NEED A BRILLIANT BARB, BOOK AN APPOINTMENT!</h2>
      </div>
    </div>
<!-- This div contains the pictures displayed in a bootstrap grid style -->
    <div class="container">
<!-- First row of pictures -->
      <div class="row">
        <div class="col-lg-3 sm-6"><img src="{% static 'images/barb1jpeg' %}" class="img-thumbnail" alt=""></div>
        <div class="col-lg-3 sm-6"><img src="{% static 'images/barb2.jpg' %}" class="img-thumbnail" alt=""></div>
        <div class="col-lg-3 sm-6"><img src="{% static 'images/barb3.jpeg' %}" class="img-thumbnail" alt=""></div>

      </div>
<!-- Second row of pictures -->
      <div class="row">
        <div class="col-lg-3 sm-6"><img src="{% static 'images/barb4.jpg' %}" class="img-thumbnail" alt=""></div>
        <div class="col-lg-3 sm-6"><img src="{% static 'images/barb5.jpg' %}" class="img-thumbnail" alt=""></div>
        <div class="col-lg-3 sm-6"><img src="{% static 'images/barb6.jpg' %}" class="img-thumbnail" alt=""></div>

      </div>
      {% endblock %}
  </body>
</html>

ProTwo/templates/appTwo/book.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>BOOKING</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
  </head>
  <body>
    <!-- navigation bar for the booking page. No inheritance for base.html -->
    <nav class="navbar navbar-expand-lg navbar-inverse">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">BACK TO HOMEPAGE</a>
        <a class="navbar-brand" href="{% url 'appTwo:clients'%}">SIGNUP</a>
      </div>
    </nav>

    <div class="container">
      <div class="jumbotron">
        <h1>GO GET A PERFECT BARB!</h1>
        <h2>BOOK AN APPOINTMENT FROM HERE!</h2>
      </div>
      <!-- contains the form for booking appointments -->
      <div class="jumbotron">
        <form method="POST" class='post-form'>
          {% csrf_token %}
          <div class="form-group">
          {{ bookform.as_p }}
        </div>
          <input type="Submit" name="submit" value="Register" class="btn btn-primary btn-lg">
        </form>
      </div>

  </div>
  </body>
</html>

ProTwo/templates/appTwo/login.html
{% extends 'appTwo/base.html' %}
{% load static %}

<!DOCTYPE html>

{% block body_block %}
 <div class="container">

<div class="jumbotron">
<h1>login here!</h1>
 <form action="{% url 'appTwo:user_login' %}" method="POST">
   {% csrf_token %}
 <!-- We did not create a specific form for our login, so we're using labels to tag them -->
 <!-- login form styled with bootstrap -->
<div class="form-group">
   <label for="username">Username: </label>
   <input type="text" class="form-control" name="username" placeholder="Username here" aria-describedby="emailHelp"><br>
 </div>
<div class="form-group">
   <label for="password">Password: </label>
   <input type="password" class="form-control" name="password" placeholder="password"><br>
 </div>

   <input type="submit" name="submit" class="btn btn-primary btn-lg" value="login">

 </form>
</div>
</div>
{% endblock %}

ProTwo/templates/appTwo/registration.html
<!-- Inheriting from base.html -->
{% extends 'appTwo/base.html' %}
<!-- loading static for the css file -->
{% load static %}
<!DOCTYPE html>

{% block body_block %}
  <div class="container">

    <div class="jumbotron">

      {% if registered %}
        <h1>Thanks for signing up!</h1>
      {% else %}
      <!-- Getting the user to sign the form -->
        <h1>Signup Here!</h1>
        <h5>By signing up, we will provide you with a user account enabling you to book appointments</h5>
    <!-- We need to add this here so that the image uploading can work -->
        <form method="POST">
          <p>the information you put here will not be shared with anyone</p>
          <!-- context variable for: username, email and password -->
          {{ client_form1.as_p }}
          <!-- context variable for: date and phone_number -->
          {{ client_form2.as_p }}
          <!-- for django security -->
          {% csrf_token %}
          <input type="Submit" name="but" class="btn btn-primary btn-lg" value="Submit">
        </form>

      {% endif %}

    </div>
  </div>
{% endblock %}