DJANGO_LEVEL_FOUR/proFour/appFour/urls.py
from django.conf.urls import url
from appFour import views

#the RELATIVE can only be specified after passing in the first extension(page2)
app_name = 'appFour'
urlpatterns = [
    url(r'^relative/$', views.relative_url, name='relative_url'),
    url(r'^$', views.page2, name='page2'),
    url(r'^base/$', views.base, name='base')
]

DJANGO_LEVEL_FOUR/proFour/proFour/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from appFour import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url('admin/', admin.site.urls),
    url(r'^page2/', include('appFour.urls')) #this is telling it to go look at the appFour folder at urls.py
]

DJANGO_LEVEL_FOUR/proFour/appFour/models.py
from django.db import models

# Create your models here.

DJANGO_LEVEL_FOUR/proFour/appFour/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):
    return render(request,'appFour/page1.html', {'text':'Im high now', 'number':123})

def page2(request):
    return render(request,'appFour/page2.html')

def relative_url(request):
    return render(request, 'appFour/relative_url_template.html')

def base(request):
    return render(request, 'appFour/base.html')

DJANGO_LEVEL_FOUR/proFour/templates/appFour/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
  </head>
  <body>
    <nav class='navabar navbar-default navbar-static-top'>
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'appFour:page2' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <!-- I just have to specify the name of the function for this one -->
          <li><a class="navbar-link" href="{% url 'index' %}">Other</a></li>
        </ul>

      </div>

    </nav>

    <div class="container">
      {% block body_block %}
      <h1>this is the base.html</h1>
      <!-- Anything outside of this block can be inherited -->
      {% endblock %}
    </div>

  </body>
</html>

DJANGO_LEVEL_FOUR/proFour/templates/appFour/page1.html
<!DOCTYPE html>
<!-- This has been inherited from the base class -->
<!-- Remove every skeleton except the doctype html -->
{% extends 'appFour/base.html'%}

  {% block body_block %}
<!-- We have created our own custom filter -->
   <h1>{{ text|cut:'high' }}</h1>
    <h1>Hello! I'm from page1</h1>
    <h1>{{ number|add:'9348' }}</h1>

    {% endblock %}

DJANGO_LEVEL_FOUR/proFour/templates/appFour/page2.html
<!DOCTYPE html>

{% extends 'appFour/base.html'%}

  {% block body_block %}
    <h1>Hello page2</h1>
    {% endblock %}

DJANGO_LEVEL_FOUR/proFour/templates/appFour/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>RELATIVE URL TEMPLATE</h1>
  <!-- THE "appFour" that I'm passing here is not from the folder name  -->
  <!-- but from the urls.py(appFour) -->
  <!-- this was for django 2.0 but it's still working -->
  <!-- avoid making spaces insdie the single quotes -->
  <a href="{% url 'appFour:page2' %}"> Go to page2</a>
<!-- django.contrib.admin is also an application created by default and has its own index -->
<!-- I have to make the migration inorder for it to work sometimes -->
  <a href="{% url 'admin:index' %}">GO TO ADMIN</a>
  <!-- And now to link to the index, it's fairly simple -->
  <a href="{% url 'index' %}">BACK TO HOMEPAGE</a>

  </body>
</html>